#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-RUnit
Version  : 0.4.32
Release  : 30
URL      : https://cran.r-project.org/src/contrib/RUnit_0.4.32.tar.gz
Source0  : https://cran.r-project.org/src/contrib/RUnit_0.4.32.tar.gz
Summary  : R Unit Test Framework
Group    : Development/Tools
License  : GPL-2.0
BuildRequires : buildreq-R

%description
framework, with additional code inspection and report
        generation tools.

%prep
%setup -q -c -n RUnit
cd %{_builddir}/RUnit

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1590012914

%install
export SOURCE_DATE_EPOCH=1590012914
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library RUnit
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library RUnit
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library RUnit
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc RUnit || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/RUnit/DESCRIPTION
/usr/lib64/R/library/RUnit/INDEX
/usr/lib64/R/library/RUnit/Meta/Rd.rds
/usr/lib64/R/library/RUnit/Meta/features.rds
/usr/lib64/R/library/RUnit/Meta/hsearch.rds
/usr/lib64/R/library/RUnit/Meta/links.rds
/usr/lib64/R/library/RUnit/Meta/nsInfo.rds
/usr/lib64/R/library/RUnit/Meta/package.rds
/usr/lib64/R/library/RUnit/Meta/vignette.rds
/usr/lib64/R/library/RUnit/NAMESPACE
/usr/lib64/R/library/RUnit/NEWS
/usr/lib64/R/library/RUnit/R/RUnit
/usr/lib64/R/library/RUnit/R/RUnit.rdb
/usr/lib64/R/library/RUnit/R/RUnit.rdx
/usr/lib64/R/library/RUnit/doc/RUnit.R
/usr/lib64/R/library/RUnit/doc/RUnit.Rnw
/usr/lib64/R/library/RUnit/doc/RUnit.pdf
/usr/lib64/R/library/RUnit/doc/index.html
/usr/lib64/R/library/RUnit/examples/correctTestCase.r
/usr/lib64/R/library/RUnit/examples/runitVirtualClassTest.r
/usr/lib64/R/library/RUnit/examples/runitc2f.r
/usr/lib64/R/library/RUnit/help/AnIndex
/usr/lib64/R/library/RUnit/help/RUnit.rdb
/usr/lib64/R/library/RUnit/help/RUnit.rdx
/usr/lib64/R/library/RUnit/help/aliases.rds
/usr/lib64/R/library/RUnit/help/paths.rds
/usr/lib64/R/library/RUnit/html/00Index.html
/usr/lib64/R/library/RUnit/html/R.css
/usr/lib64/R/library/RUnit/share/R/checkCode.r
/usr/lib64/R/library/RUnit/share/R/compareRUnitTestData.r
/usr/lib64/R/library/RUnit/tests/README
/usr/lib64/R/library/RUnit/unitTests/Makefile
/usr/lib64/R/library/RUnit/unitTests/runalltests.R
/usr/lib64/R/library/RUnit/unitTests/runitHTMLProtocol.r
/usr/lib64/R/library/RUnit/unitTests/runitInspect.r
/usr/lib64/R/library/RUnit/unitTests/runitJUnitProtocol.r
/usr/lib64/R/library/RUnit/unitTests/runitPlotConnection.r
/usr/lib64/R/library/RUnit/unitTests/runitRUnit.r
/usr/lib64/R/library/RUnit/unitTests/runitS4.r
/usr/lib64/R/library/RUnit/unitTests/runitSetUp.r
/usr/lib64/R/library/RUnit/unitTests/runitTearDown.r
/usr/lib64/R/library/RUnit/unitTests/runitTestLogger.r
/usr/lib64/R/library/RUnit/unitTests/runitTextProtocol.r
